// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pms.Adjustments.Persistence;

namespace Pms.Adjustments.Migrations
{
    [DbContext(typeof(AdjustmentDbContext))]
    [Migration("20220811130207_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Pms.Adjustments.Models.Billing", b =>
                {
                    b.Property<string>("BillingId")
                        .HasColumnType("VARCHAR(45)");

                    b.Property<string>("AdjustmentName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(45)");

                    b.Property<byte>("AdjustmentType")
                        .HasColumnType("TINYINT");

                    b.Property<double>("Amount")
                        .HasColumnType("DOUBLE(8,2)");

                    b.Property<string>("CutoffId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(6)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<byte>("Deducted")
                        .HasColumnType("TINYINT");

                    b.Property<string>("EEId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(8)");

                    b.Property<string>("RecordId")
                        .HasColumnType("VARCHAR(45)");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.HasKey("BillingId");

                    b.HasIndex("EEId");

                    b.ToTable("adjustment_billing");
                });

            modelBuilder.Entity("Pms.Adjustments.Models.EmployeeView", b =>
                {
                    b.Property<string>("EEId")
                        .HasColumnType("VARCHAR(8)");

                    b.Property<string>("BankCategory")
                        .HasColumnType("VARCHAR(45)");

                    b.Property<string>("FirstName")
                        .HasColumnType("VARCHAR(45)");

                    b.Property<string>("LastName")
                        .HasColumnType("VARCHAR(45)");

                    b.Property<string>("Location")
                        .HasColumnType("VARCHAR(45)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("VARCHAR(45)");

                    b.Property<string>("PayrollCode")
                        .HasColumnType("VARCHAR(45)");

                    b.HasKey("EEId");

                    b.ToView("masterlist");
                });

            modelBuilder.Entity("Pms.Adjustments.Models.TimesheetView", b =>
                {
                    b.Property<string>("TimesheetId")
                        .HasColumnType("varchar(767)");

                    b.Property<double>("Allowance")
                        .HasColumnType("double");

                    b.Property<string>("CutoffId")
                        .HasColumnType("text");

                    b.Property<string>("EEId")
                        .HasColumnType("text");

                    b.Property<string>("Fullname")
                        .HasColumnType("text");

                    b.Property<string>("RawPCV")
                        .HasColumnType("text");

                    b.HasKey("TimesheetId");

                    b.ToView("timesheet");
                });

            modelBuilder.Entity("Pms.Adjustments.Models.Billing", b =>
                {
                    b.HasOne("Pms.Adjustments.Models.EmployeeView", "EE")
                        .WithMany()
                        .HasForeignKey("EEId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EE");
                });
#pragma warning restore 612, 618
        }
    }
}
